[package]
name = "advent_2019"
version = "0.1.0"
authors = ["Tom Bulsink <nospam@sorrowed.nl>"]
edition = "2018"

[dependencies]
	permute = "0.1.0"
	libmath = "0.2.1"
	pathfinding = "2.0.4"
	itertools="0.9.0"